#!/usr/bin/env bash
# tests/find-fragments_spec.sh — bash-spec 2.1 tests for the
# scripts/find-fragments.sh discovery tool.
#
# Verifies that the script emits a discoverable .ncl template with
# the right header, the right sections, and the right import lines
# (paths relative to the output location).
#
# The fixture project is built under out/find-fragments/proj/ (which
# is gitignored) and recreated on each run. It lives outside the
# spec's tests/ subdir to avoid the script's own tests/ skip pattern.

cd "$(dirname "$0")"

. ./lib/bash-spec+file+jq.sh

ROOT="$(cd .. && pwd)"
SCRIPT="$ROOT/scripts/find-fragments.sh"

# Wipe and rebuild the fixture project.
rm -rf out/find-fragments
mkdir -p out/find-fragments
PROJ="$(pwd)/out/find-fragments/proj"
mkdir -p "$PROJ"/{services,overlays,goclaw}
mkdir -p "$PROJ"/tests/out
mkdir -p "$PROJ"/node_modules/dep
mkdir -p "$PROJ/build"
touch "$PROJ/compose.yml"
touch "$PROJ/goclaw/docker-compose.yml"
touch "$PROJ/goclaw/docker-compose.postgres.yml"
touch "$PROJ/services/web.yml"
touch "$PROJ/services/db.yml"
touch "$PROJ/overlays/dev.yml"
touch "$PROJ/overlays/+code.yml"
touch "$PROJ/tests/out/skipme.yml"     # should be skipped (tests/)
touch "$PROJ/build/artifact.yml"        # should be skipped (build/)
touch "$PROJ/node_modules/dep/x.yml"    # should be skipped (node_modules/)
touch "$PROJ/skip-me.bak.yml"           # should be skipped (.bak)
touch "$PROJ/example.example.yml"       # should be skipped (.example)

describe "find-fragments.sh" && {

  it "prints --help with usage" && {
    run bash "$SCRIPT" --help
    should_succeed
  }

  it "rejects unknown arguments" && {
    run bash "$SCRIPT" --bogus
    should_fail
  }

  it "emits a header on stdout" && {
    output="$(bash "$SCRIPT" --root "$PROJ")"
    expect "$output" to_match "generated by find-fragments.sh"
  }

  it "emits a runnable config wrapper (let build, let fragments, build)" && {
    output="$(bash "$SCRIPT" --root "$PROJ")"
    expect "$output" to_match 'let build = import'
    expect "$output" to_match 'let fragments = \['
    expect "$output" to_match '\] in'
    expect "$output" to_match 'build fragments'
  }

  it "auto-discovers merge.ncl when nickel-compose/ is at the project root" && {
    # Create a nickel-compose/ inside PROJ so the script can find
    # it via the first search path ($ROOT/nickel-compose/lib/...).
    mkdir -p "$PROJ/nickel-compose/lib"
    touch "$PROJ/nickel-compose/lib/merge.ncl"
    bash "$SCRIPT" --root "$PROJ" --out "$PROJ/config/found.ncl" 2>&1
    expect "$PROJ/config/found.ncl" to_exist
    output="$(cat "$PROJ/config/found.ncl")"
    expect "$output" to_match 'Merge engine: ../nickel-compose/lib/merge.ncl'
    expect "$output" to_match 'import "../nickel-compose/lib/merge.ncl"'
    rm -rf "$PROJ/nickel-compose" "$PROJ/config/found.ncl"
  }

  it "falls back to a guessed import path when no merge.ncl is found" && {
    # With no nickel-compose/ sibling, the script should still emit
    # a runnable config — the path is a best-guess that the user
    # can correct before rendering.
    bash "$SCRIPT" --root "$PROJ" --out "$PROJ/config/found.ncl" 2>&1
    expect "$PROJ/config/found.ncl" to_exist
    output="$(cat "$PROJ/config/found.ncl")"
    expect "$output" to_match 'let build = import'
    rm -f "$PROJ/config/found.ncl"
  }

  it "lists compose.yml under root section" && {
    output="$(bash "$SCRIPT" --root "$PROJ")"
    expect "$output" to_match '# === root ==='
    expect "$output" to_match '# import "compose.yml"'
  }

  it "lists docker-compose files under their directory section" && {
    output="$(bash "$SCRIPT" --root "$PROJ")"
    expect "$output" to_match '# === goclaw ==='
    expect "$output" to_match '# import "goclaw/docker-compose.yml"'
    expect "$output" to_match '# import "goclaw/docker-compose.postgres.yml"'
  }

  it "lists services/ files under services section" && {
    output="$(bash "$SCRIPT" --root "$PROJ")"
    expect "$output" to_match '# === services ==='
    expect "$output" to_match '# import "services/web.yml"'
    expect "$output" to_match '# import "services/db.yml"'
  }

  it "lists overlay files (overlays/*.yml and +code.yml)" && {
    output="$(bash "$SCRIPT" --root "$PROJ")"
    expect "$output" to_match '# import "overlays/dev.yml"'
    expect "$output" to_match '# import "overlays/.code.yml"'
  }

  it "skips tests/, build/, node_modules/, .bak, .example" && {
    output="$(bash "$SCRIPT" --root "$PROJ")"
    expect "$output" not to_match 'skipme.yml'
    expect "$output" not to_match 'artifact.yml'
    expect "$output" not to_match 'node_modules'
    expect "$output" not to_match 'skip-me.bak'
    expect "$output" not to_match 'example.example'
  }

  it "skips its own output files (compose.ncl, config.ncl, found.ncl)" && {
    # Pre-populate the fixture with files named like find-fragments
    # outputs. These share names with the script's own output paths
    # and would create self-import cycles if re-discovered.
    touch "$PROJ/compose.ncl"
    touch "$PROJ/config.ncl"
    touch "$PROJ/found.ncl"
    touch "$PROJ/config_discovered.ncl"
    output="$(bash "$SCRIPT" --root "$PROJ")"
    # Check the import lines, not the header. The header may mention
    # these names in prose.
    expect "$output" not to_match '# import "compose.ncl"'
    expect "$output" not to_match '# import "config.ncl"'
    expect "$output" not to_match '# import "found.ncl"'
    expect "$output" not to_match '# import "config_discovered.ncl"'
  }

  it "--out writes to the given path with paths relative to its dir" && {
    mkdir -p "$PROJ/config"
    run bash "$SCRIPT" --root "$PROJ" --out "$PROJ/config/found.ncl"
    should_succeed
    expect "$PROJ/config/found.ncl" to_exist
    output="$(cat "$PROJ/config/found.ncl")"
    expect "$output" to_match '# import "../compose.yml"'
    expect "$output" to_match '# import "../goclaw/docker-compose.yml"'
  }
}